# Generated by Django 2.2.12 on 2020-05-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('cholestrol', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('fiber', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('sat_fat', models.FloatField(default=0)),
            ],
        ),
    ]
